name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always
  WORKSPACE_ROOT_MANIFEST_DIR: "/home/runner/work/inexor-rgf-plugins-game/inexor-rgf-plugins-game"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
  crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Cargo Workspaces
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-workspaces
          version: latest
          use-tool-cache: true
      - name: Print environment variables
        run: |
          echo "WORKSPACE_ROOT_MANIFEST_DIR: $WORKSPACE_ROOT_MANIFEST_DIR"
      - name: Publish on crates.io
        uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: publish --from-git --allow-dirty --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          VERGEN_IDEMPOTENT: true
  debian-package:
    name: Publish debian package
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
      - name: Get version number from git tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        with:
          strip_v: true
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Cargo Deb
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          version: latest
          use-tool-cache: true
      - name: Create Debian Packages
        run: |
          # It's important to change into the plugin directory and building each package
          cd ./plugins/asset/crates/plugin
          cargo deb -p inexor-rgf-plugin-asset --target=${{ matrix.target }} --deb-version ${{steps.tag.outputs.tag}}
          # cd ../../../base/crates/plugin
          # cargo deb -p inexor-rgf-plugin-base --target=${{ matrix.target }} --deb-version ${{steps.tag.outputs.tag}}
        env:
          VERGEN_IDEMPOTENT: true
      - name: Upload debian package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/debian/libinexor-rgf-plugin-*_*_*.deb
          file_glob: true
          tag: ${{ github.ref }}
